drm
hwaccel

### xkb-options=caps:none esc:none

font-engine=pango
font-size=10
font-name=Iosevka NFM
# FiraCode Nerd Font Mono

xkb-layout=us
xkb-repeat-delay=200
xkb-repeat-rate=30

no-mouse
mouse-aspect=2.0
mouse-smoothing=0.6
mouse-scaling=0.1

dpms-timeout=600

term=xterm

sb-size=1000

palette=custom
palette-black=29,31,33
palette-red=204,101,102
palette-green=182,189,104
palette-yellow=240,198,116
palette-blue=130,162,190
palette-magenta=178,148,187
palette-cyan=138,190,183
palette-light-grey=196,200,198
palette-dark-grey=102,102,102
palette-light-red=213,78,83
palette-light-green=185,202,75
palette-light-yellow=231,197,71
palette-light-blue=122,166,218
palette-light-magenta=195,151,216
palette-light-cyan=112,192,177
palette-white=234,234,234
palette-foreground=255,255,255
palette-background=20,22,26


# cursor-color=255,255,255
# cursor-text=53,58,68
# selection-background=255,255,255
# selection-foreground=40,44,52

reset-env
