
[engon.cm]
source        = maildir://~/Mail/engon.cm
outgoing      = msmtp -a engon
default       = INBOX
from          = Engon Ken Morel <me@engon.cm>
copy-to       = Sent

[gmail.com]
source        = maildir://~/Mail/gmail.com
outgoing      = msmtp -a gmail1
default       = INBOX
from          = Engon Ken Morel <engonken8@gmail.com>
copy-to       = [Gmail]/Sent Mail

[engonkenmorel@gmail.com]
source        = maildir://~/Mail/engonkenmorel
outgoing      = msmtp -a gmail2
default       = INBOX
from          = Engon Ken Morel <engonkenmorel@gmail.com>
copy-to       = [Gmail]/Sent Mail

[cynozalabs.cm]
source        = maildir://~/Mail/cynozalabs.cm
outgoing      = msmtp -a engoncnz
default       = INBOX
from          = Engon Ken Morel <engon@cynozalabs.cm>
copy-to       = Sent
